# syntax=docker/dockerfile:1

## Build
FROM golang:1.17-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

RUN go build -o /api-server

## Deploy
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /api-server /api-server

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/api-server"]