# syntax=docker/dockerfile:1

## Build
FROM golang:1.17-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

RUN go build -o /upload-service

## Deploy
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /upload-service /upload-service

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/upload-service"]